import Head from "next/head";
import Image from "next/image";
import FrontEndLayout from "../components/layouts/frontend/FrontEndLayout";
import Hero from "../components/indexPageComponents/Hero";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FrontEndLayout>
                <div className="wrapper index-page">
                    <Hero></Hero>
                </div>
            </FrontEndLayout>
        </>
    );
}
